@extends('layout.mainlayout', ['activePage' => 'questionnaire'])

@section('title', __('Select Medicines'))

@section('css')
<link href="{{ asset('css/medicine-selection.css') }}" rel="stylesheet">
@endsection

@section('content')
<main class="main-content medicine-selection-ui">
    <!-- Breadcrumb (same structure as reference index.html) -->
    <nav class="breadcrumb">
        <a href="{{ url('/') }}" class="breadcrumb-link">{{ __('Home') }}</a>
        <svg width="16" height="16" viewBox="0 0 16 16" fill="none" class="breadcrumb-arrow">
            <path d="M6 12L10 8L6 4" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
        <a href="{{ route('categories') }}" class="breadcrumb-link">{{ __('Categories') }}</a>
        <svg width="16" height="16" viewBox="0 0 16 16" fill="none" class="breadcrumb-arrow">
            <path d="M6 12L10 8L6 4" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
        <a href="{{ route('category.detail', ['id' => $category->id]) }}" class="breadcrumb-link">{{ $category->name }}</a>
        <svg width="16" height="16" viewBox="0 0 16 16" fill="none" class="breadcrumb-arrow">
            <path d="M6 12L10 8L6 4" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
        <span class="breadcrumb-current">{{ __('Select Medicines') }}</span>
    </nav>

    <!-- Title Section (same as reference index.html) -->
    <div class="title-section">
        <h1 class="title">{{ __('Select Your Medicines') }}</h1>
        <p class="subtitle">{{ __('Choose up to 3 medicines you need for this category. Doctor can modify if needed.') }}</p>
    </div>

    <form id="medicineForm" method="POST" action="{{ route('questionnaire.save-medicine', ['categoryId' => $category->id]) }}">
        @csrf

        @if($medicines->count() > 0)
        @php
            $selectedIds = array_column($selectedMedicines ?? [], 'medicine_id');
            $medicinesForJs = $medicines->map(function ($m) {
                return [
                    'id' => (string) $m->id,
                    'name' => $m->name,
                    'subtitle' => $m->brand ? $m->brand->name : $m->name,
                    'strength' => $m->strength ?? '',
                    'form' => $m->form ?? '',
                    'image' => $m->image_url,
                ];
            })->values();
        @endphp
        <!-- Medicine Cards Grid - cards rendered by script (same as reference index.html) -->
        <div class="medicine-grid" id="medicineGrid">
            <!-- Cards will be dynamically generated by JavaScript -->
        </div>

        <!-- Info Box (same as reference index.html) -->
        <div class="info-box">
            <div class="info-content">
                <svg class="info-icon" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    <circle cx="12" cy="12" r="10"></circle>
                    <line x1="12" y1="16" x2="12" y2="12"></line>
                    <line x1="12" y1="8" x2="12.01" y2="8"></line>
                </svg>
                <p class="info-text">{{ __('You can select up to 3 medicines. The doctor will review and may modify your selection if medically required.') }}</p>
            </div>
            <p class="info-selected" id="selectedCount">{{ __('Selected') }}: {{ count($selectedIds) }} / 3</p>
        </div>

        <div class="form-actions">
            <a href="{{ $submission->delivery_type === 'delivery' ? route('questionnaire.delivery-address', ['categoryId' => $category->id]) : route('questionnaire.pharmacy-selection', ['categoryId' => $category->id]) }}" class="btn-back">{{ __('Back') }}</a>
            <button type="submit" id="medicineSubmitBtn" class="btn-continue">{{ __('Continue') }}</button>
        </div>
        @else
        <div class="info-box info-box--empty">
            <p class="info-text">{{ __('No medicines available for this category.') }}</p>
            <p class="info-text info-text--muted">{{ __('Please contact support or try another category.') }}</p>
        </div>
        <div class="form-actions">
            <a href="{{ route('category.detail', ['id' => $category->id]) }}" class="btn-back">{{ __('Back') }}</a>
        </div>
        @endif
    </form>
</main>

@if($medicines->count() > 0)
<script>
(function() {
    // Medicine data from server (same structure as reference script.js)
    const medicines = @json($medicinesForJs);
    const initialSelected = @json(array_map('strval', $selectedIds));
    let selectedMedicines = initialSelected.length ? initialSelected.slice() : [];

    const maxSelection = 3;
    const grid = document.getElementById('medicineGrid');
    const form = document.getElementById('medicineForm');
    const submitBtn = document.getElementById('medicineSubmitBtn');
    const countEl = document.getElementById('selectedCount');

    // Create medicine card HTML (same logic as reference script.js)
    function createMedicineCard(medicine) {
        const isSelected = selectedMedicines.includes(medicine.id);
        return `
            <button type="button" class="medicine-card ${isSelected ? 'selected' : ''}" data-id="${medicine.id}">
                <div class="medicine-image-container">
                    <img src="${medicine.image}" alt="${medicine.name}" class="medicine-image">
                    ${isSelected ? `
                        <div class="checkmark-badge">
                            <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M13.333 4L6 11.333L2.667 8" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                            </svg>
                        </div>
                    ` : ''}
                </div>
                <div class="medicine-content">
                    <h3 class="medicine-name">${medicine.name}</h3>
                    <p class="medicine-subtitle">${medicine.subtitle}</p>
                    <div class="medicine-details">
                        ${medicine.strength ? `
                        <div class="medicine-detail-row">
                            <span class="medicine-detail-label">{{ __('Strength') }}:</span>
                            <span class="medicine-detail-value">${medicine.strength}</span>
                        </div>
                        ` : ''}
                        ${medicine.form ? `
                        <div class="medicine-detail-row">
                            <span class="medicine-detail-label">{{ __('Form') }}:</span>
                            <span class="medicine-detail-value">${medicine.form}</span>
                        </div>
                        ` : ''}
                    </div>
                </div>
                <div class="selection-indicator ${!isSelected ? 'hidden' : ''}">
                    <div class="selection-indicator-content">
                        <p class="selection-indicator-text">✓ {{ __('SELECTED') }}</p>
                    </div>
                </div>
            </button>
        `;
    }

    // Render all medicine cards (same as reference)
    function renderMedicineCards() {
        grid.innerHTML = medicines.map(function(medicine) { return createMedicineCard(medicine); }).join('');
        var cards = grid.querySelectorAll('.medicine-card');
        cards.forEach(function(card) {
            card.addEventListener('click', function() {
                var id = card.getAttribute('data-id');
                toggleMedicine(id);
            });
        });
        updateSelectedCount();
    }

    // Toggle medicine selection (same logic as reference script.js)
    function toggleMedicine(id) {
        if (selectedMedicines.indexOf(id) !== -1) {
            selectedMedicines = selectedMedicines.filter(function(medId) { return medId !== id; });
        } else {
            if (selectedMedicines.length < maxSelection) {
                selectedMedicines.push(id);
            }
        }
        renderMedicineCards();
    }

    // Update selected count display (same as reference)
    function updateSelectedCount() {
        if (countEl) countEl.textContent = '{{ __("Selected") }}: ' + selectedMedicines.length + ' / ' + maxSelection;
    }

    // Form submit: build payload from selectedMedicines (backend expects medicines[i][medicine_id])
    form.addEventListener('submit', function(e) {
        e.preventDefault();
        if (selectedMedicines.length === 0) {
            alert('{{ __("Please select at least one medicine.") }}');
            return;
        }
        if (selectedMedicines.length > maxSelection) {
            alert('{{ __("You can select a maximum of 3 medicines.") }}');
            return;
        }
        if (submitBtn.disabled) return;
        submitBtn.disabled = true;
        submitBtn.textContent = '{{ __("Saving...") }}';
        var formData = new FormData();
        formData.append('_token', document.querySelector('meta[name="csrf-token"]').content);
        selectedMedicines.forEach(function(id, i) {
            formData.append('medicines[' + i + '][medicine_id]', id);
        });
        fetch(form.action, {
            method: 'POST',
            body: formData,
            headers: { 'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').content, 'Accept': 'application/json' }
        })
        .then(function(r) { return r.json().then(function(d) { return { ok: r.ok, data: d }; }); })
        .then(function(res) {
            if (res.ok && res.data.success) {
                window.location.href = res.data.redirect_url;
                return;
            }
            submitBtn.disabled = false;
            submitBtn.textContent = '{{ __("Continue") }}';
            alert(res.data.message || (res.data.errors && JSON.stringify(res.data.errors)) || '{{ __("An error occurred. Please try again.") }}');
        })
        .catch(function() {
            submitBtn.disabled = false;
            submitBtn.textContent = '{{ __("Continue") }}';
            alert('{{ __("An error occurred. Please try again.") }}');
        });
    });

    // Initialize (same as reference: renderMedicineCards on DOMContentLoaded)
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', renderMedicineCards);
    } else {
        renderMedicineCards();
    }
})();
</script>
@endif
@endsection
