START TRANSACTION;
INSERT INTO category (name, treatment_id, status) VALUES ('Erektionsstörungen', 1, 1);
INSERT INTO category (name, treatment_id, status) VALUES ('Vorzeitiger Samenerguss', 1, 1);
INSERT INTO category (name, treatment_id, status) VALUES ('Haarausfall', 1, 1);
INSERT INTO category (name, treatment_id, status) VALUES ('Testosteronmangel', 1, 1);
INSERT INTO category (name, treatment_id, status) VALUES ('Verhütung', 2, 1);
INSERT INTO category (name, treatment_id, status) VALUES ('Gesichtsbehaarung', 2, 1);
INSERT INTO category (name, treatment_id, status) VALUES ('Bakterielle Vaginose', 2, 1);
INSERT INTO category (name, treatment_id, status) VALUES ('Blasenentzündung', 2, 1);
INSERT INTO category (name, treatment_id, status) VALUES ('Gardnerella vaginalis', 2, 1);
INSERT INTO category (name, treatment_id, status) VALUES ('Scheidenpilz', 2, 1);
INSERT INTO category (name, treatment_id, status) VALUES ('Wechseljahre', 2, 1);
INSERT INTO category (name, treatment_id, status) VALUES ('Chlamydien', 3, 1);
INSERT INTO category (name, treatment_id, status) VALUES ('Genitalwarzen', 3, 1);
INSERT INTO category (name, treatment_id, status) VALUES ('Genitalherpes', 3, 1);
INSERT INTO category (name, treatment_id, status) VALUES ('HIV Prävention (PrEP)', 3, 1);
INSERT INTO category (name, treatment_id, status) VALUES ('Gonorrhoe', 3, 1);
INSERT INTO category (name, treatment_id, status) VALUES ('Ureaplasma', 3, 1);
INSERT INTO category (name, treatment_id, status) VALUES ('Mycoplasma', 3, 1);
INSERT INTO category (name, treatment_id, status) VALUES ('Candida', 3, 1);
INSERT INTO category (name, treatment_id, status) VALUES ('Trichomonaden', 3, 1);
INSERT INTO category (name, treatment_id, status) VALUES ('Medizinisches Cannabis', 4, 1);
INSERT INTO category (name, treatment_id, status) VALUES ('STI Tests', 5, 1);
INSERT INTO category (name, treatment_id, status) VALUES ('Akne', 6, 1);
INSERT INTO category (name, treatment_id, status) VALUES ('Lippenherpes', 6, 1);
INSERT INTO category (name, treatment_id, status) VALUES ('Rosacea', 6, 1);
INSERT INTO category (name, treatment_id, status) VALUES ('Asthma', 7, 1);
INSERT INTO category (name, treatment_id, status) VALUES ('Allergischer Schnupfen', 7, 1);
INSERT INTO category (name, treatment_id, status) VALUES ('Raucherentwöhnung', 7, 1);
INSERT INTO category (name, treatment_id, status) VALUES ('Migräne', 7, 1);
INSERT INTO category (name, treatment_id, status) VALUES ('Sodbrennen', 7, 1);
INSERT INTO category (name, treatment_id, status) VALUES ('Bluthochdruck', 7, 1);
INSERT INTO category (name, treatment_id, status) VALUES ('Diabetes Typ 2', 7, 1);
INSERT INTO category (name, treatment_id, status) VALUES ('Übergewicht', 7, 1);
INSERT INTO category (name, treatment_id, status) VALUES ('Hohes Cholesterin', 7, 1);
INSERT INTO category (name, treatment_id, status) VALUES ('Vitamin-D-Mangel', 7, 1);
INSERT INTO category (name, treatment_id, status) VALUES ('Schilddrüsenunterfunktion', 7, 1);
INSERT INTO category (name, treatment_id, status) VALUES ('Schmerzen', 7, 1);
INSERT INTO category (name, treatment_id, status) VALUES ('Malariaprophylaxe', 8, 1);
INSERT INTO category (name, treatment_id, status) VALUES ('Reisedurchfall', 8, 1);
COMMIT;